CREATE DATABASE IF NOT EXISTS School;

CREATE TABLE IF NOT EXISTS classroom (
id_class BIGINT(20) PRIMARY KEY NOT NULL AUTO_INCREMENT,
id_school BIGINT(20) NOT NULL, 
class_name VARCHAR(20) NOT NULL, 
class_year YEAR,
form_tutor_id BIGINT(20) NOT NULL
);
