CREATE TABLE student (
  STUDENT_ID INT AUTO_INCREMENT NOT NULL,
  FIRST_NAME VARCHAR(20)        NOT NULL,
  LAST_NAME  VARCHAR(20)        NOT NULL,
  AGE        INT                NOT NULL,
  PRIMARY KEY (STUDENT_ID)
);

